[package]
name = "rust-persian-tools"
version = "0.1.0"
edition = "2021"


[dependencies]
urlencoding = {version = "2.1.3", optional = true}


[features]
default = []

add-ordinal-suffix = []
commas = []
digits = []
find-capital-by-province = []
is-persian = []
national-id = []
remove-ordinal-suffix = []
to-persian-chars = []
url-fix = ["dep:urlencoding"]
verity-card-number = []
